# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-04 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jason2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(db_column='Date')),
                ('time', models.CharField(db_column='Time', max_length=10)),
                ('water_level', models.FloatField(db_column='Water_Level')),
                ('station', models.CharField(choices=[('vsg1', 'Gauge Station 1'), ('vsg2', 'Gauge Station 2'), ('vsg3', 'Gauge Station 3'), ('vsg4', 'Gauge Station 4'), ('vsg5', 'Gauge Station 5'), ('vsg6', 'Gauge Station 6'), ('vsg7', 'Gauge Station 7'), ('vsg8', 'Gauge Station 8'), ('vsg9', 'Gauge Station 9'), ('vsg10', 'Gauge Station 10'), ('vsg11', 'Gauge Station 11'), ('vsg12', 'Gauge Station 12'), ('vsg13', 'Gauge Station 13'), ('vsg14', 'Gauge Station 14'), ('vsg15', 'Gauge Station 15'), ('vsg16', 'Gauge Station 16'), ('vsg17', 'Gauge Station 17'), ('vsg18', 'Gauge Station 18'), ('vsg19', 'Gauge Station 19'), ('vsg20', 'Gauge Station 20'), ('vsg21', 'Gauge Station 21'), ('vsg22', 'Gauge Station 22')], db_column='Station', max_length=5)),
            ],
            options={
                'db_table': '"jason2"',
            },
        ),
        migrations.CreateModel(
            name='Jason3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(db_column='Date')),
                ('time', models.CharField(db_column='Time', max_length=10)),
                ('water_level', models.FloatField(db_column='Water_Level')),
                ('station', models.CharField(choices=[('vsg1', 'Gauge Station 1'), ('vsg2', 'Gauge Station 2'), ('vsg3', 'Gauge Station 3'), ('vsg4', 'Gauge Station 4'), ('vsg5', 'Gauge Station 5'), ('vsg6', 'Gauge Station 6'), ('vsg7', 'Gauge Station 7'), ('vsg8', 'Gauge Station 8'), ('vsg9', 'Gauge Station 9'), ('vsg10', 'Gauge Station 10'), ('vsg11', 'Gauge Station 11'), ('vsg12', 'Gauge Station 12'), ('vsg13', 'Gauge Station 13'), ('vsg14', 'Gauge Station 14'), ('vsg15', 'Gauge Station 15'), ('vsg16', 'Gauge Station 16'), ('vsg17', 'Gauge Station 17'), ('vsg18', 'Gauge Station 18'), ('vsg19', 'Gauge Station 19'), ('vsg20', 'Gauge Station 20'), ('vsg21', 'Gauge Station 21'), ('vsg22', 'Gauge Station 22')], db_column='Station', max_length=5)),
            ],
            options={
                'db_table': '"jason3"',
            },
        ),
    ]
