# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-27 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_gauge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jason3',
            name='gdr',
            field=models.BooleanField(default=False),
        ),
    ]
